Style/LineLength:
  Description: 'Limit lines to 120 characters.'
  Max: 120
Style/StringLiterals:
  EnforcedStyle: single_quotes
Style/EmptyLinesAroundBody:
  Enabled: false
Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation
