base: &default
  sessions:
    default:
      uri: <%= ENV['JIRA_CACHE_MONGODB_URI'] %>

production:
  <<: *default

development:
  <<: *default

test:
  sessions:
    default:
      uri: <%= ENV['JIRA_CACHE_MONGODB_URI'] %>_test
      safe: true
